experiment:
  seed: 88
  save_dir: ../experiments/


data: 
  annotations: ../data/train_2dc_classes_kfold.csv
  data_dir: ../data/
  input: filename
  target: [large_bowel, small_bowel, stomach, gi_tract]
  outer_fold: 0
  dataset:
    name: ImageDataset
    params:
      channels: 2dc
      flip: true
      invert: false
      verbose: true


transform:
  resize:
    name: resize_ignore
    params:
      imsize: [512, 512]
  augment:
    name: simple_augment_with_dropout
    params:
      n: 3
      p: 1.0
  crop:
    null
  preprocess: 
    name: Preprocessor
    params:
      image_range: [0, 255]
      input_range: [0, 1]
      mean: [0.5, 0.5, 0.5]
      sdev: [0.5, 0.5, 0.5]


task: 
  name: ClassificationTask
  params: 
    mixaug:
      mixup: 0.4


model:
  name: Net2D
  params:
    backbone: tf_efficientnet_b6_ns
    pretrained: true
    num_classes: 4
    dropout: 0.2
    pool: avg
    in_channels: 1
    multisample_dropout: true


loss:
  name: MixBCE
  params:


optimizer:
  name: AdamW
  params:
    lr: 3.0e-4
    weight_decay: 5.0e-4


scheduler: 
  name: CosineAnnealingLR
  params:
    final_lr: 0.0


train:
  batch_size: 16
  num_epochs: 5


evaluate: 
  metrics: [AUROC]
  monitor: auc_mean
  mode: max


