experiment:
  seed: 88
  save_dir: ../experiments/


data:
  annotations: ../data/train_chunk_features_kfold.csv
  data_dir: ../data/chunk-features
  input: filename
  target: [C1, C2, C3, C4, C5, C6, C7, patient_overall]
  outer_fold: 0
  dataset:
    name: FeatureDataset
    params:
      seq_len: 7
      reverse: true
      exam_level_label: true


task:
  name: ClassificationTask
  params:


model:
  name: Transformer
  params:
    num_classes: 8
    embedding_dim: 432
    hidden_dim: 864
    n_layers: 3
    n_heads: 16
    predict_sequence: false


loss:
  name: CompetitionMetric
  params:


optimizer:
  name: RAdam
  params:
    lr: 1.0e-3
    weight_decay: 5.0e-4


scheduler:
  name: CosineAnnealingLR
  params:
    final_lr: 1.0e-5


train:
  batch_size: 32
  num_epochs: 25


evaluate:
  batch_size: 1
  metrics: [CompetitionMetric]
  monitor: comp_metric
  mode: min


