experiment:
  seed: 88
  save_dir: ../experiments/


data:
  annotations: ../data/train_seq_kfold.csv
  data_dir: ../data/train-cas002-features/foldx/
  input: filename
  target: [C1, C2, C3, C4, C5, C6, C7, patient_overall]
  outer_fold: 0
  dataset:
    name: FeatureDataset
    params:
      seq_len: 192
      resample: true
      reverse: true
      exam_level_label: true


task:
  name: ClassificationTask
  params:


model:
  name: Transformer
  params:
    num_classes: 8
    embedding_dim: 256
    hidden_dim: 512
    n_layers: 3
    n_heads: 16
    predict_sequence: false


loss:
  name: BCEWithLogitsLoss
  params:
    pos_weight: 2.0


optimizer:
  name: AdamW
  params:
    lr: 1.0e-4
    weight_decay: 5.0e-4


scheduler:
  name: CosineAnnealingLR
  params:
    final_lr: 0


train:
  batch_size: 32
  num_epochs: 25


evaluate:
  batch_size: 1
  metrics: [CompetitionMetric]
  monitor: comp_metric
  mode: min


