experiment:
  seed: 88
  save_dir: ../experiments/


data:
  annotations: ../data/train_dual_seq_kfold.csv
  data_dir: ../data/train-cas001-features/foldx/
  input: filename
  target: label
  outer_fold: 0
  dataset:
    name: DualFeatureDataset
    params:
      seq_len: 128
      resample: true
      reverse: true


task:
  name: ClassificationTask
  params:


model:
  name: DualTransformerV2
  params:
    num_seq_classes: 1
    num_classes: 8
    embedding_dim: 2304
    hidden_dim: 2304
    n_layers: 3
    n_heads: 16


loss:
  name: DualFeatureSequenceBCELoss
  params:
    weights: [0.5, 0.5]
    simple_bce_params:
      pos_weight: 2.0
    weighted_bce_params:
      pos_weight: 2.0
      weights: [1, 1, 1, 1, 1, 1, 1, 7]


optimizer:
  name: AdamW
  params:
    lr: 1.0e-5
    weight_decay: 5.0e-4


scheduler:
  name: CosineAnnealingLR
  params:
    final_lr: 0


train:
  batch_size: 32
  num_epochs: 25


evaluate:
  batch_size: 1
  metrics: [CompetitionMetric, AUROC]
  monitor: comp_metric
  mode: min


